version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/protobuf"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/cpp_format_tools"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/schemas"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/schemas"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/semantic-conventions"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/semantic-conventions"
    schedule:
      interval: "weekly"
