version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
