name: Semantic Convention Generator Docker Image
on:
  push:
    tags: [ '**' ]
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/semconvgen-dockerimage.yml
      - 'semantic-conventions/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build semantic-conventions/. -t semconvgen
    - name: Push the Docker image
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        function tag_and_push {
          docker tag semconvgen "otel/semconvgen:${1}" && docker push "otel/semconvgen:${1}"
        }
        if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
          tag_and_push "latest"
        elif [[ "${GITHUB_REF}" =~ refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            TAG="${GITHUB_REF#"refs/tags/v"}"
            tag_and_push "${TAG}"
        else
          tag_and_push "${GITHUB_REF#"refs/tags/"}"
        fi